/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.LichDao;
import model.TangCa;
import model.TangCaDao;
import model.User;
import model.UserDao;

/**
 *
 * @author qivub
 */
public class DangKyTangCaFrame extends javax.swing.JFrame {
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    DefaultTableModel model;
    TangCaDao dao = new TangCaDao();
    
    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
    /**
     * Creates new form DangKyTangCaJFrame
     */
    public DangKyTangCaFrame() {
        
        initComponents();
        an();
        model = (DefaultTableModel) tbList.getModel();
        System.out.println(model.getColumnCount());
        fillDataTABLE();
    }
    
    public void fillDataTABLE() {
        model.setRowCount(0); // Xóa tất cả các dòng hiện tại trong bảng
        for (TangCa ls : dao.getTangCaforUser()) {
            Object rowData[] = new Object[8];
            rowData[0] = ls.getId();
            rowData[1] = ls.getMaNV();
            rowData[2] = ls.getTenNV();
            rowData[3] = ls.getNgayNhan();
            if (ls.getCaLam()== 0) {
                rowData[4] = "Đang Làm";
            }  
            rowData[5] = ls.getGioVao();
            rowData[6] = ls.getGioRa();
            rowData[7] = ls.getThoiGianLam();
            
            model.addRow(rowData);
        }
    }
    public void setModel(TangCa tc){
        int row = tbList.getSelectedRow();
        txtIDCV.setText((String) tbList.getValueAt(row, 0));
        txtMaNV.setText((String) tbList.getValueAt(row,1));
        txtTenNV.setText((String) tbList.getValueAt(row, 2));
        Object value = tbList.getValueAt(row, 3);
        if (value != null) {
            if (value instanceof java.sql.Date) {
                java.sql.Date deadlineDate = (java.sql.Date) value;
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                String ngaynhan = dateFormat.format(deadlineDate);

               
                txtNgayNhan.setText(ngaynhan);
            } 
        }
        Object rawValue = (String) tbList.getValueAt(row, 4);
            if (rawValue instanceof Integer) {
            int ca = (int) rawValue;
            tc.setCaLam(ca);
                if(ca == 1 ){
                    rdCatoi.setSelected(true);
                }
            }
        Time gioVao = (Time) tbList.getValueAt(row, 5);
        txtGioVao.setText(sdf.format(gioVao)); 
        Time gioRa  = (Time) tbList.getValueAt(row, 6);
        txtGioRa.setText(sdf.format(gioRa));
        Time tglam  = (Time) tbList.getValueAt(row, 7);
        txtThoiGianLam.setText(sdf.format(tglam));
        
    }
    private void updateTotalGiolam() {
    
        Time giovao = Time.valueOf(txtGioVao.getText() + ":00");
        Time giora = Time.valueOf(txtGioRa.getText() + ":00");

        long milliseconds = giora.getTime() - giovao.getTime();
        Duration duration = Duration.ofMillis(milliseconds);

        long hours = duration.toHours();
        long minutes = duration.minusHours(hours).toMinutes();

        String formattedTime = String.format("%02d:%02d", hours, minutes);
        txtThoiGianLam.setText(formattedTime);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnDangKyTangCa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIDCV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayNhan = new javax.swing.JTextField();
        txtGioVao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGioRa = new javax.swing.JTextField();
        rdCatoi = new javax.swing.JRadioButton();
        btnSua1 = new javax.swing.JButton();
        btnMain1 = new javax.swing.JButton();
        btnLuu1 = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        txtThoiGianLam = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtSearchTC = new javax.swing.JTextField();
        btnSearchTC = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtFindMaNV = new javax.swing.JTextField();
        btnSearchMaNv = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pnListNV = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbList = new javax.swing.JTable();
        lblDanhSach = new javax.swing.JLabel();
        lblDangKyTangCa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnDangKyTangCa.setBackground(new java.awt.Color(255, 255, 255));
        pnDangKyTangCa.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("IDCV");

        txtIDCV.setEditable(false);
        txtIDCV.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Mã Nhân Viên");

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Tên NV");

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Giờ vào");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Ngày Nhận");

        txtNgayNhan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtGioVao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Giờ ra");

        txtGioRa.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        rdCatoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdCatoi.setSelected(true);
        rdCatoi.setText("Ca Tối");

        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes.png"))); // NOI18N
        btnSua1.setText("Gia Hạn");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnMain1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.png"))); // NOI18N
        btnMain1.setText("Home");
        btnMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMain1ActionPerformed(evt);
            }
        });

        btnLuu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        btnLuu1.setText("Đăng Ký");
        btnLuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu1ActionPerformed(evt);
            }
        });

        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        btnThem1.setText("Clear");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        txtThoiGianLam.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtThoiGianLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiGianLamActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Thời Gian Làm");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setText("Tìm kiếm");

        btnSearchTC.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSearchTC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        btnSearchTC.setText("Tìm Kiếm IDCV");
        btnSearchTC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTCbtnTimKiemActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setText("Tìm kiếm");

        txtFindMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearchMaNv.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSearchMaNv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        btnSearchMaNv.setText("Tìm kiếm Mã Nhân Viên");
        btnSearchMaNv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchMaNv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMaNvbtnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFindMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSearchMaNv)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtFindMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchMaNv))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDangKyTangCaLayout = new javax.swing.GroupLayout(pnDangKyTangCa);
        pnDangKyTangCa.setLayout(pnDangKyTangCaLayout);
        pnDangKyTangCaLayout.setHorizontalGroup(
            pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtSearchTC, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchTC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                        .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtThoiGianLam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGioRa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNgayNhan, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtGioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdCatoi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                        .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDCV, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLuu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        pnDangKyTangCaLayout.setVerticalGroup(
            pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(btnSearchTC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                        .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua1))
                        .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnThem1)
                                .addGap(18, 18, 18)
                                .addComponent(btnLuu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMain1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGioVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnDangKyTangCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGioRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(pnDangKyTangCaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(rdCatoi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThoiGianLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPanel1.add(pnDangKyTangCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 660));

        pnListNV.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        tbList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã NV", "TênNV", "Ngày nhận", "Ca", "Giờ Vào", "Giờ Ra", "Thời Gian Làm"
            }
        ));
        tbList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbList);

        javax.swing.GroupLayout pnListNVLayout = new javax.swing.GroupLayout(pnListNV);
        pnListNV.setLayout(pnListNVLayout);
        pnListNVLayout.setHorizontalGroup(
            pnListNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(pnListNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnListNVLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );
        pnListNVLayout.setVerticalGroup(
            pnListNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(pnListNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnListNVLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(pnListNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 620));

        lblDanhSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDanhSach.setText("Danh Sách NV Tăng Ca");
        lblDanhSach.setBorder(new javax.swing.border.MatteBorder(null));
        lblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDanhSachMouseClicked(evt);
            }
        });

        lblDangKyTangCa.setBackground(new java.awt.Color(255, 255, 255));
        lblDangKyTangCa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangKyTangCa.setText("Đăng Ký Tăng Ca");
        lblDangKyTangCa.setBorder(new javax.swing.border.MatteBorder(null));
        lblDangKyTangCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangKyTangCaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDanhSach)
                    .addComponent(lblDangKyTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblDangKyTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void an(){
        pnDangKyTangCa.setVisible(false);
        pnListNV.setVisible(false);
    }
    private void lblDangKyTangCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangKyTangCaMouseClicked
        // TODO add your handling code here:
        pnDangKyTangCa.setVisible(true);
        pnListNV.setVisible(false);
        
    }//GEN-LAST:event_lblDangKyTangCaMouseClicked

    private void lblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhSachMouseClicked
        pnDangKyTangCa.setVisible(false);
        pnListNV.setVisible(true);
        
    }//GEN-LAST:event_lblDanhSachMouseClicked
    public TangCa getModel() throws ParseException {
            
            TangCa tca = new TangCa();
            tca.setId(txtIDCV.getText());
            tca.setMaNV(txtMaNV.getText());
            tca.setTenNV(txtTenNV.getText());
            String batdau = txtGioVao.getText();
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");

                Date gioVao = sdf.parse(batdau);
                if (gioVao != null) {
                    Time gioVaoTime = new Time(gioVao.getTime());
                    tca.setGioVao(gioVaoTime);
                } else {
                    System.err.println("Lỗi: Ngày giờ không hợp lệ");
                    JOptionPane.showMessageDialog(this, "Lỗi: Ngày giờ không hợp lệ");
                }
            } catch (ParseException e) {
                e.printStackTrace();
                System.err.println("Lỗi: Không thể chuyển đổi ngày giờ");
            }

            String ketthuc = txtGioRa.getText();
            try {
                // Sử dụng định dạng "HH:mm" thay vì "HH:mm:ss"
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");

                Date gioRa = sdf.parse(ketthuc);
                if (gioRa != null) {
                    // Chuyển đổi Date thành Time
                    Time gioRaTime = new Time(gioRa.getTime());
                    tca.setGioRa(gioRaTime);
                } else {
                    System.err.println("Lỗi: Ngày giờ không hợp lệ");
                    JOptionPane.showMessageDialog(this, "Lỗi: Ngày giờ không hợp lệ");
                }
            } catch (ParseException e) {
                e.printStackTrace();
                System.err.println("Lỗi: Không thể chuyển đổi ngày giờ");
            }


            String ngaynhan = txtNgayNhan.getText();
            try {
                Date nhanviec = dateFormat.parse(ngaynhan);
                if (nhanviec != null) {
                    tca.setNgayNhan(nhanviec);
                } else {
                    System.err.println("Lỗi: Ngày hết hạn không hợp lệ");
                }
            } catch (ParseException e) {
                e.printStackTrace();
            }
            if (rdCatoi.isSelected()) {
                tca.setCaLam(0);
            }
            String thoigianlam = txtThoiGianLam.getText();
            try {
                // Sử dụng định dạng "HH:mm" thay vì "HH:mm:ss"
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");

                Date tglam = sdf.parse(thoigianlam);
                if (tglam != null) {
                    // Chuyển đổi Date thành Time
                    Time thoiGianLam = new Time(tglam.getTime());
                    tca.setThoiGianLam(thoiGianLam);
                } else {
                    System.err.println("Lỗi: Ngày giờ không hợp lệ");
                    JOptionPane.showMessageDialog(this, "Lỗi: Ngày giờ không hợp lệ");
                }
            } catch (ParseException e) {
                e.printStackTrace();
                System.err.println("Lỗi: Không thể chuyển đổi ngày giờ");
            }
            
            return tca;
        }
    public boolean validateForm(){
//        if (txtIDCV.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Id Chưa Nhập");
//            return false;
//        }else 
            if (txtMaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã Nhân Viên Chưa Nhập");
            return false;
        }else if (txtTenNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên NV Chưa Nhập");
            return false;
        }else if (txtNgayNhan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có ngày nhận");
            return false;
        }else if (txtGioRa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có giờ tan ca");
            return false;
        }else if (txtGioVao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có giờ nhận ca");
            return false;
        }else if (txtThoiGianLam.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa có thời gian làm");
            return false;
        }
        return true;
    }   
    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        if (validateForm()) {
            try {
                TangCa tg = getModel();
                if (dao.update(tg)>0){
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    fillDataTABLE();
                }
            } catch (ParseException ex) {

            }
        }else{
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin ");
        }
         
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMain1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnMain1ActionPerformed

    private void btnLuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu1ActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            try {
                TangCa lich= getModel();
                if (dao.add(lich)>0) {
                    JOptionPane.showMessageDialog(this, "Lưu thành công! ");
                    fillDataTABLE();
                }
            } catch (ParseException ex) {

            }
        }else{

            JOptionPane.showMessageDialog(this, "Chưa nhập đủ! ");
        }
    }//GEN-LAST:event_btnLuu1ActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
//        txtIDNhanCV.setText("");
//        txtMaNVNhan.setText("");
//        txtSearchDLGiao.setText("");
//        txtSearchDLGiao.setText("");
//        txtNhanCongViec.setText("");
//        txtNhanND.setText("");
//        rdChuahoanthanh.setSelected(true);
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnSearchTCbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTCbtnTimKiemActionPerformed
        if (txtSearchTC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã Công Việc");
        }else{
            TangCa tangca = dao.getIDChamCongByID(txtSearchTC.getText());
            txtIDCV.setText(tangca.getId());
            txtMaNV.setText(tangca.getMaNV());
            txtTenNV.setText(tangca.getTenNV());
            Date ngayNhan = tangca.getNgayNhan();
            String ngaynhan = dateFormat.format(ngayNhan);
            Time gioVao = tangca.getGioVao();
            String gioVaoString = sdf.format(gioVao);
            Time gioRa = tangca.getGioRa();
            String gioRaString = sdf.format(gioRa);
            Time tgLam = tangca.getThoiGianLam();
            String tgString = sdf.format(tgLam);
            Object rawValue = tangca.getCaLam();
            if (rawValue instanceof Integer) {
            int ca = (int) rawValue;
            tangca.setCaLam(ca);
                if(ca == 1 ){
                    rdCatoi.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_btnSearchTCbtnTimKiemActionPerformed

    private void btnSearchMaNvbtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMaNvbtnTimKiemActionPerformed
        if (txtFindMaNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã Nhân Viên");
        }else{
            LichDao daoo = new LichDao();
            User nv = daoo.getNhanVienByID(txtFindMaNV.getText());
            txtMaNV.setText(nv.getMaNV());
            txtTenNV.setText(nv.getTenNV());
        }
    }//GEN-LAST:event_btnSearchMaNvbtnTimKiemActionPerformed

    private void tbListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMouseClicked
         
            int id = tbList.rowAtPoint(evt.getPoint());
            String idtc = tbList.getValueAt(id, 0).toString();
            TangCa tc = dao.getIDChamCongByID(idtc);
            setModel(tc);
    }//GEN-LAST:event_tbListMouseClicked

    private void txtThoiGianLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiGianLamActionPerformed
        // TODO add your handling code here:
        updateTotalGiolam();
    }//GEN-LAST:event_txtThoiGianLamActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        if (validateForm()) {
            try {
                TangCa nv = getModel();
                if (dao.del(nv)>0){
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    fillDataTABLE();
                }
            } catch (ParseException ex) {
                Logger.getLogger(NhanVienMainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin ");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyTangCaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyTangCaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyTangCaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyTangCaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyTangCaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu1;
    private javax.swing.JButton btnMain1;
    private javax.swing.JButton btnSearchMaNv;
    private javax.swing.JButton btnSearchTC;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDangKyTangCa;
    private javax.swing.JLabel lblDanhSach;
    private javax.swing.JPanel pnDangKyTangCa;
    private javax.swing.JPanel pnListNV;
    private javax.swing.JRadioButton rdCatoi;
    private javax.swing.JTable tbList;
    private javax.swing.JTextField txtFindMaNV;
    private javax.swing.JTextField txtGioRa;
    private javax.swing.JTextField txtGioVao;
    private javax.swing.JTextField txtIDCV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayNhan;
    private javax.swing.JTextField txtSearchTC;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtThoiGianLam;
    // End of variables declaration//GEN-END:variables
}
